site_name: My Docs
site_url: https://fabi7006.github.io/chemistry/
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: deep purple

markdown_extensions:
  - md_in_html
  - pymdownx.blocks.caption
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - toc

extra:
  social:
    - icon: simple/instagram
      link: https://www.instagram.com/fabi_7006/

copyright: Copyright &copy; 2024 Fabian Polscheit

plugins:
  - search